#ifndef frameIDALL_
#define frameIDALL_

#define AENC @"AENC|CRA Audio encryption"
#define APIC @"APIC|PIC Attached picture"
#define ASPI @"ASPI Audio seek point index"
#define COMM @"COMM|COM Comments"
#define COMR @"COMR Commercial frame"
#define ENCR @"ENCR Encryption method registration"
#define EQU2 @"EQU2 Equalisation (2)"
#define ETCO @"ETCO|ETC Event timing codes"
#define GEOB @"GEOB|GEO General encapsulated object"
#define GRID @"GRID Group identification registration"
#define LINK @"LINK|LNK Linked information"
#define MCDI @"MCDI|MCI Music CD identifier"
#define MLLT @"MLLT|MLL MPEG location lookup table"
#define OWNE @"OWNE Ownership frame"
#define PRIV @"PRIV Private frame"
#define PCNT @"PCNT|CNT Play counter"
#define POPM @"POPM|POP Popularimeter"
#define POSS @"POSS Position synchronisation frame"
#define RBUF @"RBUF|BUF Recommended buffer size"
#define RVA2 @"RVA2 Relative volume adjustment (2)"
#define RVRB @"RVRB|REV Reverb"
#define SEEK @"SEEK Seek frame"
#define SIGN @"SIGN Signature frame"
#define SYLT @"SYLT Synchronised lyric/text"
#define SYTC @"SYTC Synchronised tempo codes"
#define TALB @"TALB|TAL Album/Movie/Show title"
#define TBPM @"TBPM|TBP BPM (beats per minute)"
#define TCOM @"TCOM|TCM Composer"
#define TCON @"TCON|TCO Content type"
#define TCOP @"TCOP|TCR Copyright message"
#define TDEN @"TDEN Encoding time"
#define TDLY @"TDLY|TDY Playlist delay"
#define TDOR @"TDOR Original release time"
#define TDRC @"TDRC Recording time"
#define TDRL @"TDRL Release time"
#define TDTG @"TDTG Tagging time"
#define TENC @"TENC|TEN Encoded by"
#define TEXT @"TEXT|TXT Lyricist/Text writer"
#define TFLT @"TFLT|TFT File type"
#define TIPL @"TIPL|IPL Involved people list"
#define TIT1 @"TIT1|TT1 Content group description"
#define TIT2 @"TIT2|TT2 Title/songname/content description"
#define TIT3 @"TIT3|TT3 Subtitle/Description refinement"
#define TKEY @"TKEY|TKE Initial key"
#define TLAN @"TLAN|TLA Language(s)"
#define TLEN @"TLEN|TLE Length"
#define TMCL @"TMCL Musician credits list"
#define TMED @"TMED|TMT Media type"
#define TMOO @"TMOO Mood"
#define TOAL @"TOAL|TOT Original album/movie/show title"
#define TOFN @"TOFN|TOF Original filename"
#define TOLY @"TOLY|TOL Original lyricist(s)/text writer(s)"
#define TOPE @"TOPE|TOA Original artist(s)/performer(s)"
#define TOWN @"TOWN File owner/licensee"
#define TPE1 @"TPE1 Lead performer(s)/Soloist(s)"
#define TPE2 @"TPE2|TP2 Band/orchestra/accompaniment"
#define TPE3 @"TPE3|TP3 Conductor/performer refinement"
#define TPE4 @"TPE4|TP4 Interpreted, remixed, or otherwise modified by"
#define TPOS @"TPOS|TPA Part of a set"
#define TPRO @"TPRO Produced notice"
#define TPUB @"TPUB|TPB Publisher"
#define TRCK @"TRCK|TRK Track number/Position in set"
#define TRSN @"TRSN Internet radio station name"
#define TRSO @"TRSO Internet radio station owner"
#define TSOA @"TSOA Album sort order"
#define TSOP @"TSOP Performer sort order"
#define TSOT @"TSOT Title sort order"
#define TSRC @"TSRC|TRC ISRC (international standard recording code)"
#define TSSE @"TSSE|TSS Software/Hardware and settings used for encoding"
#define TSST @"TSST Set subtitle"
#define TXXX @"TXXX|TXX User defined text information frame"
#define UFID @"UFID|UFI Unique file identifier"
#define USER @"USER Terms of use"
#define USLT @"USLT Unsynchronised lyric/text transcription"
#define WCOM @"WCOM|WCM Commercial information"
#define WCOP @"WCOP|WCP Copyright/Legal information"
#define WOAF @"WOAF|WAF Official audio file webpage"
#define WOAR @"WOAR|WAR Official artist/performer webpage"
#define WOAS @"WOAS|WAS Official audio source webpage"
#define WORS @"WORS Official Internet radio station homepage"
#define WPAY @"WPAY Payment"
#define WPUB @"WPUB|WPB Publishers official webpage"
#define WXXX @"WXXX|WXX User defined URL link frame"
#define CRM @"CRM Encrypted meta frame"
#define EQU @"EQUA|EQU Equalization"
#define RVA @"RVAD|RVA Relative volume adjustment"
#define SLT @"SLT Synchronized lyric/text"
#define STC @"STC Synced tempo codes"
#define TDA @"TDAT|TDA Date"
#define TIM @"TIME|TIM Time"
#define TOR @"TORY|TOR Original release year"
#define TP1 @"TP1 Lead artist(s)/Lead performer(s)/Soloist(s)/Performing group"
#define TRD @"TRDA|TRD Recording dates"
#define TSI @"TSIZ|TSI Size"
#define TYE @"TYER|TYE Year"
#define ULT @"ULT Unsychronized lyric/text transcription"

#endif
